"""update with new changes

Revision ID: 35df0a8621bc
Revises: 49ac2aa96ac0
Create Date: 2025-07-01 22:57:04.966020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35df0a8621bc'
down_revision: Union[str, Sequence[str], None] = '49ac2aa96ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payload',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('context_devices_id_fkey'), 'context', type_='foreignkey')
    op.drop_column('context', 'media_files')
    op.drop_column('context', 'telemetry_files')
    op.drop_column('context', 'devices_id')
    op.drop_column('context', 'log_files')
    op.add_column('flights', sa.Column('software_id', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('radio_device', sa.Integer(), nullable=True))
    op.add_column('flights', sa.Column('autopilot_device', sa.Integer(), nullable=True))
    op.add_column('flights', sa.Column('servo_device', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flights', 'devices', ['autopilot_device'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flights', 'devices', ['radio_device'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flights', 'devices', ['servo_device'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flights', 'software', ['software_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_column('flights', 'servo_device')
    op.drop_column('flights', 'autopilot_device')
    op.drop_column('flights', 'radio_device')
    op.drop_column('flights', 'software_id')
    op.add_column('context', sa.Column('log_files', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('context', sa.Column('devices_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('context', sa.Column('telemetry_files', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('context', sa.Column('media_files', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('context_devices_id_fkey'), 'context', 'devices', ['devices_id'], ['id'], ondelete='CASCADE')
    op.drop_table('payload')
    # ### end Alembic commands ###
